# config
cover: /img/bg_img.jpg
logo: /img/kiros.png
top_saying:
- title: YOU'VE MADE A <span>BRAVE</span> DECISION, WELCOME.
- content: 每一个不曾起舞的日子都是对生命的辜负。
bottom_saying: Whatever is worth doing is worth doing well.
# Content
excerpt_link: Read More

rss: /atom.xml
about: /about.html

highlightjs: vs

#Works
#works:
#- works_name: AAA
#  works_url: /
#- works_name: BBB
#  works_url: /atom.xml

#duoshuo name
duoshuo: kiroswu

# Miscellaneous
github: https://github.com/kiroswu
twitter: https://twitter.com/
facebook: https://www.facebook.com/
google: https://google.com/
weibo: http://weibo.com/u/2363324471

#about  timeline
timeline:
- num: 1
  word: 2009/09/01-步入大学第一天，软件工程专业，拥有了第一台电脑，学会了开机。
- num: 2
  word: 2009/09/24-学会了C，第一个Hello World。
- num: 3
  word: 2013/01/04-人生第一份工作，上海魔都。
- num: 4
  word: More

#Links
links:
- name: Kiros
  link: http://kirosblog.cn/
- name: Name
  link: http://domain.com/