# config
cover: /img/bg_img.jpg
logo: /img/kiros.png
top_saying:
- title: YOU'VE MADE A <span>BRAVE</span> DECISION, WELCOME.
- content: 每一个不曾起舞的日子都是对生命的辜负。
bottom_saying: Whatever is worth doing is worth doing well.
# Content
excerpt_link: Read More

rss: /atom.xml

highlightjs: vs

#Works
#works:
#- works_name: AAA
#  works_url: /
#- works_name: BBB
#  works_url: /atom.xml

#duoshuo name
duoshuo: kiroswu

# Miscellaneous
github: https://github.com/kiroswu
twitter: https://twitter.com/
facebook: https://www.facebook.com/
google: https://google.com/
weibo: http://weibo.com/u/2363324471

#about  timeline
timeline:
- num: 1
  word: 2014/06/12-Start
- num: 2
  word: 2014/11/29-XXX
- num: 3
  word: 2015/02/18-DDD
- num: 4
  word: More

#Links
links:
- name: Kieran
  link: http://go.kieran.top/
- name: Name
  link: http://domain.com/